global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
      - targets: ['localhost:9090']

  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
  - job_name: 'authentication'
    static_configs:
      - targets: ["host.docker.internal:8080"]
      - targets: ['authentication:3001']

  - job_name: 'pari'
    static_configs:
      - targets: ['pari:3000']
